title: Xiao Zheng's personal page
description: My Personal Stack Problems
author: xiaogit
github: https://github.com/xiaogit
about: An adventurer knocked into the world of C/C++. A ranger came from the mysterious forest NO.1037. A meditator waiting for one to come by the side of his shoulders. 
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-skype
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"

share:
  twitter_username: agusmakmun6
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Github
      url: https://github.com/xiaogit
    - text: XML Feed
      url: /feed.xml

url: "https://xiaogit.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist